"""add progress column to runs

Revision ID: cba825265365
Revises: f4990d3fbc19
Create Date: 2026-07-27 09:33:15.525136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cba825265365'
down_revision: Union[str, Sequence[str], None] = 'f4990d3fbc19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows so the NOT NULL add doesn't fail
    # against a populated table; dropped after backfill since the model's
    # default is applied at the application layer, not the schema layer.
    op.add_column('runs', sa.Column('progress', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('runs', 'progress', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'progress')
    # ### end Alembic commands ###
